version: "3"
services:
  mongo:
    image: mongo:5.0.5
    container_name: mongodb
    environment:
      - MONGO_INIT_DATABASE=mgo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb-volume:/data/db
      - ./migration:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - "27017:27017"
    restart: always

  web:
    container_name: go_server
    build: .
    image: server
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./cmd/:/config
    command: [ "-confile",  "/config/config.yaml" ]
    depends_on:
      - mongo

volumes:
  mongodb-volume:
